<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SecureChat.ClientCore\SecureChat.ClientCore.csproj" />
    <ProjectReference Include="..\SecureChat.Core\SecureChat.Core.csproj" />
    <ProjectReference Include="..\SecureChat.Shared\SecureChat.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="appsettings.client.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
